### ISSUE TITLE
doesn't work anymore

### ISSUE THREAD

**Issue by lebed2045** [rawsp33d/webgl-rts#2]
Immediately after install got an error:

```
500 Error: /Users/lebedkin/programming/temp/webgl-rts/views/layout.jade:1 > 1| doctype 5 2| html 3| head 4| title= title `doctype 5` is deprecated, you must now use `doctype html`
> 1| doctype 5
2| html
3| head
4| title= title
`doctype 5` is deprecated, you must now use `doctype html`
at Object.Lexer.doctype (/Users/lebedkin/programming/temp/webgl-rts/node_modules/jade/lib/lexer.js:256:13)
at Object.Lexer.next (/Users/lebedkin/programming/temp/webgl-rts/node_modules/jade/lib/lexer.js:916:15)
at Object.Lexer.lookahead (/Users/lebedkin/programming/temp/webgl-rts/node_modules/jade/lib/lexer.js:113:46)
at Parser.lookahead (/Users/lebedkin/programming/temp/webgl-rts/node_modules/jade/lib/parser.js:102:23)
at Parser.peek (/Users/lebedkin/programming/temp/webgl-rts/node_modules/jade/lib/parser.js:79:17)
at Parser.parse (/Users/lebedkin/programming/temp/webgl-rts/node_modules/jade/lib/parser.js:117:26)
at Parser.parse (/Users/lebedkin/programming/temp/webgl-rts/node_modules/jade/lib/parser.js:131:24)
at parse (/Users/lebedkin/programming/temp/webgl-rts/node_modules/jade/lib/index.js:104:21)
at Object.exports.compile (/Users/lebedkin/programming/temp/webgl-rts/node_modules/jade/lib/index.js:205:16)
at handleTemplateCache (/Users/lebedkin/programming/temp/webgl-rts/node_modules/jade/lib/index.js:174:25)
```

**Comment by rosshadden** [comment]
Thanks
